import { type CanvasNode, type CanvasEdge } from "@/types/canvas"

export interface CanvasTemplate {
  id: string
  name: string
  description: string
  nodes: CanvasNode[]
  edges: CanvasEdge[]
}

export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  {
    id: "microservices",
    name: "Microservices",
    description:
      "API Gateway routes traffic to isolated services, each backed by a dedicated database and connected via a shared message bus.",
    nodes: [
      {
        id: "gateway",
        type: "canvasNode",
        position: { x: 80, y: 170 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Gateway", color: "#10233D", shape: "rectangle" },
      },
      {
        id: "orchestrator",
        type: "canvasNode",
        position: { x: 230, y: 170 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Orchestrator", color: "#062822", shape: "pill" },
      },
      {
        id: "broker",
        type: "canvasNode",
        position: { x: 230, y: 280 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Event Broker", color: "#2E1938", shape: "hexagon" },
      },
      // Services Stack
      {
        id: "svc-auth",
        type: "canvasNode",
        position: { x: 380, y: 60 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Auth Svc", color: "#2E1938", shape: "rectangle" },
      },
      {
        id: "svc-users",
        type: "canvasNode",
        position: { x: 380, y: 130 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "User Svc", color: "#2E1938", shape: "rectangle" },
      },
      {
        id: "svc-orders",
        type: "canvasNode",
        position: { x: 380, y: 200 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Order Svc", color: "#2E1938", shape: "rectangle" },
      },
      {
        id: "svc-inventory",
        type: "canvasNode",
        position: { x: 380, y: 270 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Stock Svc", color: "#2E1938", shape: "rectangle" },
      },
      // Databases Stack
      {
        id: "db-auth",
        type: "canvasNode",
        position: { x: 530, y: 60 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Auth DB", color: "#1F1F1F", shape: "cylinder" },
      },
      {
        id: "db-users",
        type: "canvasNode",
        position: { x: 530, y: 130 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "User DB", color: "#1F1F1F", shape: "cylinder" },
      },
      {
        id: "db-orders",
        type: "canvasNode",
        position: { x: 530, y: 200 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Order DB", color: "#1F1F1F", shape: "cylinder" },
      },
      {
        id: "db-inventory",
        type: "canvasNode",
        position: { x: 530, y: 270 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Stock DB", color: "#1F1F1F", shape: "cylinder" },
      },
    ],
    edges: [
      {
        id: "e-gw-orch",
        source: "gateway",
        sourceHandle: "right",
        target: "orchestrator",
        targetHandle: "left",
        type: "canvasEdge",
      },
      // Orchestrator to services
      {
        id: "e-orch-auth",
        source: "orchestrator",
        sourceHandle: "right",
        target: "svc-auth",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-orch-users",
        source: "orchestrator",
        sourceHandle: "right",
        target: "svc-users",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-orch-orders",
        source: "orchestrator",
        sourceHandle: "right",
        target: "svc-orders",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-orch-inv",
        source: "orchestrator",
        sourceHandle: "right",
        target: "svc-inventory",
        targetHandle: "left",
        type: "canvasEdge",
      },
      // Broker to services
      {
        id: "e-brk-auth",
        source: "broker",
        sourceHandle: "right",
        target: "svc-auth",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-brk-users",
        source: "broker",
        sourceHandle: "right",
        target: "svc-users",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-brk-orders",
        source: "broker",
        sourceHandle: "right",
        target: "svc-orders",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-brk-inv",
        source: "broker",
        sourceHandle: "right",
        target: "svc-inventory",
        targetHandle: "left",
        type: "canvasEdge",
      },
      // Services to Databases
      {
        id: "e-auth-db",
        source: "svc-auth",
        sourceHandle: "right",
        target: "db-auth",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-users-db",
        source: "svc-users",
        sourceHandle: "right",
        target: "db-users",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-orders-db",
        source: "svc-orders",
        sourceHandle: "right",
        target: "db-orders",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-inv-db",
        source: "svc-inventory",
        sourceHandle: "right",
        target: "db-inventory",
        targetHandle: "left",
        type: "canvasEdge",
      },
    ],
  },
  {
    id: "cicd-pipeline",
    name: "CI/CD Pipeline",
    description:
      "End-to-end delivery from source commit through build, test, containerisation, and staged deployment to production.",
    nodes: [
      {
        id: "source",
        type: "canvasNode",
        position: { x: 100, y: 150 },
        width: 90,
        height: 50,
        style: { width: 90, height: 50 },
        data: { label: "Source", color: "#10233D", shape: "rectangle" },
      },
      {
        id: "build",
        type: "canvasNode",
        position: { x: 230, y: 150 },
        width: 90,
        height: 50,
        style: { width: 90, height: 50 },
        data: { label: "Build", color: "#062822", shape: "rectangle" },
      },
      {
        id: "test",
        type: "canvasNode",
        position: { x: 360, y: 150 },
        width: 90,
        height: 50,
        style: { width: 90, height: 50 },
        data: { label: "Test", color: "#331B00", shape: "rectangle" },
      },
      {
        id: "registry",
        type: "canvasNode",
        position: { x: 490, y: 150 },
        width: 90,
        height: 50,
        style: { width: 90, height: 50 },
        data: { label: "Registry", color: "#2E1938", shape: "rectangle" },
      },
      {
        id: "staging",
        type: "canvasNode",
        position: { x: 620, y: 150 },
        width: 90,
        height: 50,
        style: { width: 90, height: 50 },
        data: { label: "Staging", color: "#3A1726", shape: "rectangle" },
      },
      {
        id: "production",
        type: "canvasNode",
        position: { x: 750, y: 150 },
        width: 90,
        height: 50,
        style: { width: 90, height: 50 },
        data: { label: "Production", color: "#3C1618", shape: "diamond" },
      },
    ],
    edges: [
      {
        id: "e-src-bld",
        source: "source",
        sourceHandle: "right",
        target: "build",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-bld-tst",
        source: "build",
        sourceHandle: "right",
        target: "test",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-tst-reg",
        source: "test",
        sourceHandle: "right",
        target: "registry",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-reg-stg",
        source: "registry",
        sourceHandle: "right",
        target: "staging",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-stg-prd",
        source: "staging",
        sourceHandle: "right",
        target: "production",
        targetHandle: "left",
        type: "canvasEdge",
      },
    ],
  },
  {
    id: "event-driven",
    name: "Event-Driven System",
    description:
      "Producers publish events to a central bus. Independent consumers handle emails, push notifications, analytics, and error queues.",
    nodes: [
      // Left stack
      {
        id: "producer-web",
        type: "canvasNode",
        position: { x: 100, y: 110 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Web Client", color: "#10233D", shape: "rectangle" },
      },
      {
        id: "producer-mobile",
        type: "canvasNode",
        position: { x: 100, y: 190 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Mobile Client", color: "#10233D", shape: "rectangle" },
      },
      // Center
      {
        id: "bus",
        type: "canvasNode",
        position: { x: 260, y: 145 },
        width: 100,
        height: 60,
        style: { width: 100, height: 60 },
        data: { label: "Event Bus", color: "#2E1938", shape: "hexagon" },
      },
      // Consumers stack
      {
        id: "cons-email",
        type: "canvasNode",
        position: { x: 420, y: 50 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Email Svc", color: "#0F2E18", shape: "rectangle" },
      },
      {
        id: "cons-push",
        type: "canvasNode",
        position: { x: 420, y: 120 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Push Svc", color: "#0F2E18", shape: "rectangle" },
      },
      {
        id: "cons-analytics",
        type: "canvasNode",
        position: { x: 420, y: 190 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Analytics", color: "#0F2E18", shape: "rectangle" },
      },
      {
        id: "cons-logging",
        type: "canvasNode",
        position: { x: 420, y: 260 },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
        data: { label: "Logger", color: "#0F2E18", shape: "rectangle" },
      },
      // Far right stack
      {
        id: "q-email",
        type: "canvasNode",
        position: { x: 580, y: 50 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Email Out", color: "#1F1F1F", shape: "rectangle" },
      },
      {
        id: "q-push",
        type: "canvasNode",
        position: { x: 580, y: 120 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Push Out", color: "#1F1F1F", shape: "rectangle" },
      },
      {
        id: "q-analytics",
        type: "canvasNode",
        position: { x: 580, y: 190 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Analytics Store", color: "#1F1F1F", shape: "rectangle" },
      },
      {
        id: "q-logging",
        type: "canvasNode",
        position: { x: 580, y: 260 },
        width: 80,
        height: 50,
        style: { width: 80, height: 50 },
        data: { label: "Log Archive", color: "#1F1F1F", shape: "rectangle" },
      },
    ],
    edges: [
      {
        id: "e-web-bus",
        source: "producer-web",
        sourceHandle: "right",
        target: "bus",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-mob-bus",
        source: "producer-mobile",
        sourceHandle: "right",
        target: "bus",
        targetHandle: "left",
        type: "canvasEdge",
      },
      // Bus to consumers
      {
        id: "e-bus-email",
        source: "bus",
        sourceHandle: "right",
        target: "cons-email",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-bus-push",
        source: "bus",
        sourceHandle: "right",
        target: "cons-push",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-bus-anl",
        source: "bus",
        sourceHandle: "right",
        target: "cons-analytics",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-bus-log",
        source: "bus",
        sourceHandle: "right",
        target: "cons-logging",
        targetHandle: "left",
        type: "canvasEdge",
      },
      // Consumers to queues
      {
        id: "e-email-q",
        source: "cons-email",
        sourceHandle: "right",
        target: "q-email",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-push-q",
        source: "cons-push",
        sourceHandle: "right",
        target: "q-push",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-anl-q",
        source: "cons-analytics",
        sourceHandle: "right",
        target: "q-analytics",
        targetHandle: "left",
        type: "canvasEdge",
      },
      {
        id: "e-log-q",
        source: "cons-logging",
        sourceHandle: "right",
        target: "q-logging",
        targetHandle: "left",
        type: "canvasEdge",
      },
    ],
  },
]
